"""One-click backend starter scaffolds for NXT1 runtimes.

Generates a minimal, working backend with:
  - GET /api/health         → {"status": "ok"}
  - POST /api/echo          → echoes JSON body back
  - CORS enabled
  - PORT env support

Two flavours: FastAPI (python) and Express (node).
"""
from typing import List, Dict


def _fastapi_starter() -> List[Dict[str, str]]:
    server_py = '''"""FastAPI starter generated by NXT1.

Runs at http://127.0.0.1:$PORT (default 8000).
Health: GET /api/health
Echo:   POST /api/echo  body: any JSON
"""
import os
from fastapi import FastAPI, Body
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="NXT1 backend starter")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    return {"status": "ok", "service": "fastapi"}


@app.get("/api/hello")
def hello(name: str = "world"):
    return {"hello": name}


@app.post("/api/echo")
def echo(payload: dict = Body(default={})):
    return {"you_sent": payload}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="127.0.0.1", port=port)
'''
    requirements = "fastapi==0.110.1\nuvicorn==0.30.1\n"
    readme = '''# Backend (FastAPI)

Generated by NXT1. Edit `backend/server.py` to add routes.

## Endpoints
- `GET /api/health` — health check
- `GET /api/hello?name=Foo` — sample
- `POST /api/echo` — echo JSON body

## Run locally
```
cd backend && pip install -r requirements.txt
uvicorn server:app --reload --port 8000
```

NXT1 runs this in a sandboxed subprocess automatically. Use the
**Runtime** tab to start/stop and view logs.
'''
    return [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": requirements},
        {"path": "backend/README.md", "content": readme},
    ]


def _express_starter() -> List[Dict[str, str]]:
    server_js = '''// Express starter generated by NXT1.
// Health: GET /api/health
// Echo:   POST /api/echo
const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", (req, res) => {
  res.json({ status: "ok", service: "express" });
});

app.get("/api/hello", (req, res) => {
  res.json({ hello: req.query.name || "world" });
});

app.post("/api/echo", (req, res) => {
  res.json({ you_sent: req.body });
});

const port = process.env.PORT || 3001;
app.listen(port, "127.0.0.1", () => {
  console.log(`✓ NXT1 backend (express) running on :${port}`);
});
'''
    package_json = '''{
  "name": "nxt1-backend",
  "version": "0.1.0",
  "private": true,
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.19.2",
    "cors": "^2.8.5"
  }
}
'''
    readme = '''# Backend (Node/Express)

Generated by NXT1. Edit `backend/server.js` to add routes.

## Endpoints
- `GET /api/health`
- `GET /api/hello?name=Foo`
- `POST /api/echo`

## Run locally
```
cd backend && npm install && node server.js
```

NXT1 runs this in a sandboxed subprocess automatically. Use the
**Runtime** tab to start/stop and view logs.
'''
    return [
        {"path": "backend/server.js", "content": server_js},
        {"path": "backend/package.json", "content": package_json},
        {"path": "backend/README.md", "content": readme},
    ]


def build_starter(kind: str) -> List[Dict[str, str]]:
    kind = (kind or "").lower()
    if kind in ("fastapi", "python", "py"):
        return _fastapi_starter()
    if kind in ("express", "node", "js", "node-express"):
        return _express_starter()
    raise ValueError(f"Unknown starter kind: {kind}")


def merge_into_files(existing: List[dict], new_files: List[dict]) -> List[dict]:
    """Merge starter files into existing project files. Existing files at the
    same path are overwritten only if they're empty or missing.
    """
    by_path = {f["path"]: dict(f) for f in (existing or [])}
    for nf in new_files:
        prev = by_path.get(nf["path"])
        if prev and (prev.get("content") or "").strip():
            # Don't clobber non-empty user files; rename instead
            base, dot, ext = nf["path"].rpartition(".")
            new_path = f"{base}.starter.{ext}" if dot else f"{nf['path']}.starter"
            by_path[new_path] = {"path": new_path, "content": nf["content"]}
        else:
            by_path[nf["path"]] = nf
    return list(by_path.values())
