/**
 * NXT1 / Agents — workspace-only browser for the unified Agents + OpenClaw
 * catalog (243 entries · 78 categories at time of writing).
 *
 * What it is
 * ----------
 * One quiet, dense, theme-aware catalog page that combines:
 *   • 191 specialised AI agents from wshobson/agents (Claude Code plugins)
 *   • 52 OpenClaw skills (personal-assistant primitives — Notion, GitHub,
 *     iMessage, Discord, etc.)
 *
 * Source data flows through `GET /api/agents/catalog`, generated by
 * `backend/scripts/build_agents_catalog.py` (regenerable any time the
 * upstream repos change).
 *
 * Design
 * ------
 * - Workspace-only. Reached from the side drawer.
 * - Theme-aware (carbon dark / tan light, NXT1 tokens throughout).
 * - Category rail on the left (desktop) or a flat dropdown (mobile).
 * - Live, instant client-side search across name + description.
 * - Kind chips (Agent · Skill) for filtering by surface.
 * - No public listing — auth required at the API.
 *
 * What this page DOES NOT do (intentional)
 * ---------------------------------------
 * - No agent runtime. The user said: keep both backends separate.
 *   This page is a browse + categorise surface ONLY. Running agents
 *   from this UI is a follow-on phase once you've wired API keys.
 */
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Search, Layers, Cpu, Sparkles, ChevronRight, Loader2, Star } from "lucide-react";
import api from "@/lib/api";
import { useTheme } from "@/components/theme/ThemeProvider";
import AgentInvokePanel from "@/components/agents/AgentInvokePanel";

const KIND_META = {
  agent: { label: "Agent", icon: Cpu,       hint: "AI sub-agent · code/dev" },
  skill: { label: "Skill", icon: Sparkles,  hint: "OpenClaw skill · personal assistant" },
};

const SOURCE_META = {
  agents:   { label: "Agents",   sub: "wshobson · 80 plugins · 185 agents" },
  openclaw: { label: "OpenClaw", sub: "openclaw · 53 skills · personal AI" },
};

// Top 8 — the agents/skills builders reach for most. Anchored by id so
// renames upstream don't quietly drop the row. If any one is missing
// from the catalog we just hide that tile.
const TOP_PICKS = [
  "agent::backend-development::backend-architect",
  "agent::frontend-mobile-development::frontend-developer",
  "agent::security-compliance::security-auditor",
  "agent::backend-development::test-automator",
  "agent::code-refactoring::code-reviewer",
  "agent::cicd-automation::devops-troubleshooter",
  "skill::github",
  "skill::notion",
];

export default function AgentsPage() {
  const { theme } = useTheme();
  const isLight = theme === "light";
  const [catalog, setCatalog] = useState(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");
  const [q, setQ] = useState("");
  const [category, setCategory] = useState("All");
  const [kind, setKind] = useState("all");
  const [openItem, setOpenItem] = useState(null);

  useEffect(() => {
    setLoading(true);
    api.get("/agents/catalog")
      .then((r) => setCatalog(r.data))
      .catch((e) => setErr(e?.response?.data?.detail || "Failed to load catalog"))
      .finally(() => setLoading(false));
  }, []);

  // Derive category list + counts client-side so the rail counts update
  // when the kind filter changes.
  const { categories, filtered } = useMemo(() => {
    if (!catalog) return { categories: [], filtered: [] };
    const items = catalog.items || [];
    const kindFiltered = kind === "all" ? items : items.filter((i) => i.kind === kind);
    const counts = new Map();
    for (const it of kindFiltered) {
      counts.set(it.category, (counts.get(it.category) || 0) + 1);
    }
    const cats = [
      { name: "All", count: kindFiltered.length },
      ...Array.from(counts.entries())
        .map(([name, count]) => ({ name, count }))
        .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name)),
    ];
    let pool = category === "All" ? kindFiltered : kindFiltered.filter((i) => i.category === category);
    if (q.trim()) {
      const needle = q.trim().toLowerCase();
      pool = pool.filter((i) =>
        i.name.toLowerCase().includes(needle) ||
        (i.description || "").toLowerCase().includes(needle) ||
        i.slug.toLowerCase().includes(needle),
      );
    }
    return { categories: cats, filtered: pool };
  }, [catalog, q, category, kind]);

  const accent = isLight ? "#0E7C66" : "#5EEAD4";

  return (
    <div
      className="w-full max-w-[1180px] mx-auto px-5 sm:px-8 py-8 sm:py-12"
      data-testid="agents-page"
    >
      {/* Header */}
      <header className="mb-8 sm:mb-10">
        <div className="flex items-center gap-2 mb-3">
          <span
            className="mono text-[10.5px] tracking-[0.32em] uppercase font-medium"
            style={{ color: "var(--nxt-fg-faint)" }}
          >
            Workspace · Agents
          </span>
        </div>
        <h1
          className="text-[34px] sm:text-[44px] leading-[1.02] tracking-[-0.025em] font-medium"
          style={{ fontFamily: "'Cabinet Grotesk', sans-serif", color: "var(--nxt-fg)" }}
        >
          A library of specialised agents and skills.
        </h1>
        <p
          className="mt-3 max-w-[640px] text-[14px] sm:text-[15px] leading-relaxed"
          style={{ color: "var(--nxt-fg-dim)" }}
        >
          A combined catalogue of build-time AI agents (orchestration, code
          review, infra, security) and personal-assistant skills (messaging,
          notes, calendar, github). Browse, search, and pin the ones you
          want NXT1 to summon for you.
        </p>

        {/* Source attribution chips */}
        <div className="mt-5 flex flex-wrap gap-2">
          {Object.entries(SOURCE_META).map(([key, meta]) => (
            <div
              key={key}
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full"
              style={{
                background: "var(--nxt-chip-bg)",
                border: "1px solid var(--nxt-chip-border)",
              }}
              data-testid={`agents-source-chip-${key}`}
            >
              <span
                className="mono text-[10.5px] tracking-[0.18em] uppercase font-medium"
                style={{ color: "var(--nxt-fg)" }}
              >
                {meta.label}
              </span>
              <span className="text-[11px]" style={{ color: "var(--nxt-fg-faint)" }}>
                {meta.sub}
              </span>
            </div>
          ))}
        </div>
      </header>

      {/* Search + kind filter row */}
      <div className="mb-8 sm:mb-10 flex flex-col sm:flex-row gap-3">
        <div
          className="flex-1 flex items-center gap-2.5 h-11 rounded-xl px-3.5"
          style={{
            background: "var(--nxt-surface-soft)",
            border: "1px solid var(--nxt-border-soft)",
          }}
        >
          <Search size={14} style={{ color: "var(--nxt-fg-faint)" }} />
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search 243 agents & skills…"
            className="flex-1 bg-transparent text-[13.5px] outline-none placeholder:opacity-50"
            style={{ color: "var(--nxt-fg)" }}
            data-testid="agents-search"
          />
          {q && (
            <button
              onClick={() => setQ("")}
              className="text-[11px] mono opacity-60 hover:opacity-100"
              style={{ color: "var(--nxt-fg)" }}
            >
              clear
            </button>
          )}
        </div>
        <div className="flex items-center gap-2">
          {[
            { id: "all",   label: "All" },
            { id: "agent", label: "Agents" },
            { id: "skill", label: "Skills" },
          ].map((k) => (
            <button
              key={k.id}
              onClick={() => setKind(k.id)}
              className="h-11 px-4 rounded-xl text-[12.5px] font-medium tracking-tight transition-all"
              style={{
                background: kind === k.id ? "var(--nxt-fg)" : "var(--nxt-surface-soft)",
                color:      kind === k.id ? "var(--nxt-surface-soft)" : "var(--nxt-fg)",
                border:     `1px solid ${kind === k.id ? "var(--nxt-fg)" : "var(--nxt-border-soft)"}`,
              }}
              data-testid={`agents-kind-${k.id}`}
            >
              {k.label}
            </button>
          ))}
        </div>
      </div>

      {loading && (
        <div className="flex items-center gap-2 py-12 justify-center" style={{ color: "var(--nxt-fg-dim)" }}>
          <Loader2 size={14} className="animate-spin" />
          <span className="mono text-[12px] tracking-wider">Loading catalog…</span>
        </div>
      )}

      {err && (
        <div
          className="rounded-xl p-5 text-center mono text-[12px]"
          style={{
            background: "var(--nxt-surface-soft)",
            border: "1px solid rgba(244, 63, 94, 0.30)",
            color: "var(--nxt-fg)",
          }}
        >
          {err}
        </div>
      )}

      {!loading && !err && catalog && (
        <>
          {/* Top 8 curated row */}
          <TopPicks
            catalog={catalog}
            accent={accent}
            onOpen={(it) => setOpenItem(it)}
          />

          <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] gap-6 lg:gap-10">
          {/* Category rail */}
          <aside className="md:sticky md:top-6 md:self-start max-h-[80vh] overflow-y-auto">
            <div
              className="mono text-[10px] tracking-[0.30em] uppercase mb-2.5 px-1"
              style={{ color: "var(--nxt-fg-faint)" }}
            >
              Categories
            </div>
            <ul className="space-y-0.5">
              {categories.map((c) => {
                const active = c.name === category;
                return (
                  <li key={c.name}>
                    <button
                      onClick={() => setCategory(c.name)}
                      className="w-full flex items-center justify-between gap-2 px-3 py-2 rounded-lg text-left transition"
                      style={{
                        background: active ? "var(--nxt-surface-soft)" : "transparent",
                        border: `1px solid ${active ? "var(--nxt-border-soft)" : "transparent"}`,
                      }}
                      data-testid={`agents-cat-${c.name.replace(/\s+/g, "-").toLowerCase()}`}
                    >
                      <span
                        className="text-[12.5px] truncate"
                        style={{
                          color: active ? "var(--nxt-fg)" : "var(--nxt-fg-dim)",
                          fontWeight: active ? 500 : 400,
                        }}
                      >
                        {c.name}
                      </span>
                      <span
                        className="mono text-[10.5px] shrink-0"
                        style={{ color: "var(--nxt-fg-faint)" }}
                      >
                        {c.count}
                      </span>
                    </button>
                  </li>
                );
              })}
            </ul>
          </aside>

          {/* Cards grid */}
          <section>
            <div className="flex items-baseline justify-between mb-4">
              <span
                className="mono text-[11px] tracking-[0.28em] uppercase"
                style={{ color: "var(--nxt-fg-faint)" }}
              >
                {filtered.length} {filtered.length === 1 ? "result" : "results"}
                {category !== "All" && (
                  <span style={{ color: "var(--nxt-fg-dim)" }}> · {category}</span>
                )}
              </span>
            </div>
            {filtered.length === 0 ? (
              <div
                className="rounded-2xl p-10 text-center"
                style={{
                  background: "var(--nxt-surface-soft)",
                  border: "1px solid var(--nxt-border-soft)",
                  color: "var(--nxt-fg-dim)",
                }}
              >
                <Layers size={18} className="mx-auto opacity-50 mb-3" />
                <p className="text-[13px]">Nothing matches that filter yet.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                {filtered.map((item) => (
                  <AgentCard key={item.id} item={item} accent={accent} onOpen={() => setOpenItem(item)} />
                ))}
              </div>
            )}
          </section>
        </div>
        </>
      )}

      {/* Invocation slide-over */}
      <AgentInvokePanel
        open={!!openItem}
        item={openItem}
        onClose={() => setOpenItem(null)}
      />

      {/* Footer — workspace-only attribution */}
      <footer
        className="mt-16 pt-6 text-[11px] mono tracking-wider"
        style={{
          color: "var(--nxt-fg-faint)",
          borderTop: "1px solid var(--nxt-border-soft)",
        }}
      >
        Catalogue assembled from <a href="https://github.com/wshobson/agents" target="_blank" rel="noreferrer" className="underline hover:no-underline">wshobson/agents</a>
        {" · "}
        <a href="https://github.com/openclaw/openclaw" target="_blank" rel="noreferrer" className="underline hover:no-underline">openclaw/openclaw</a>.
        Connect your own keys to invoke them.{" "}
        <Link to="/workspace/providers" className="underline hover:no-underline">
          Open provider settings →
        </Link>
      </footer>
    </div>
  );
}

function TopPicks({ catalog, accent, onOpen }) {
  const byId = useMemo(() => {
    const m = new Map();
    for (const it of catalog?.items || []) m.set(it.id, it);
    return m;
  }, [catalog]);
  const picks = TOP_PICKS.map((id) => byId.get(id)).filter(Boolean);
  if (!picks.length) return null;
  return (
    <section className="mb-10" data-testid="agents-top-picks">
      <div className="flex items-center gap-2 mb-3">
        <Star size={12} style={{ color: accent }} />
        <span
          className="mono text-[10.5px] tracking-[0.32em] uppercase font-medium"
          style={{ color: "var(--nxt-fg-faint)" }}
        >
          Top picks for builders
        </span>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
        {picks.map((item) => {
          const Icon = KIND_META[item.kind]?.icon || Layers;
          return (
            <button
              key={item.id}
              type="button"
              onClick={() => onOpen?.(item)}
              className="group rounded-xl p-3.5 text-left transition-all hover:-translate-y-0.5"
              style={{
                background: "var(--nxt-surface-soft)",
                border: "1px solid var(--nxt-border-soft)",
              }}
              data-testid={`agents-top-pick-${item.id.replace(/[^\w-]/g, "_")}`}
            >
              <div className="flex items-center justify-between mb-2">
                <span
                  className="h-7 w-7 rounded-lg flex items-center justify-center"
                  style={{
                    background: "var(--nxt-chip-bg)",
                    border: "1px solid var(--nxt-border-soft)",
                  }}
                >
                  <Icon size={11} style={{ color: accent }} />
                </span>
                <span
                  className="mono text-[9.5px] tracking-[0.22em] uppercase opacity-60"
                  style={{ color: "var(--nxt-fg-faint)" }}
                >
                  {KIND_META[item.kind]?.label}
                </span>
              </div>
              <h4
                className="text-[12.5px] font-medium tracking-tight truncate"
                style={{ color: "var(--nxt-fg)" }}
              >
                {item.name}
              </h4>
              <p
                className="text-[11.5px] leading-snug mt-0.5 line-clamp-2"
                style={{ color: "var(--nxt-fg-dim)" }}
              >
                {item.description}
              </p>
            </button>
          );
        })}
      </div>
    </section>
  );
}

function AgentCard({ item, accent, onOpen }) {
  const Icon = KIND_META[item.kind]?.icon || Layers;
  return (
    <article
      className="group rounded-2xl p-4 transition-all hover:-translate-y-0.5 cursor-pointer"
      style={{
        background: "var(--nxt-surface-soft)",
        border: "1px solid var(--nxt-border-soft)",
      }}
      onClick={onOpen}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onOpen?.(); } }}
      data-testid={`agents-card-${item.id.replace(/[^\w-]/g, "_")}`}
    >
      <div className="flex items-start justify-between gap-3 mb-2">
        <div className="flex items-center gap-2 min-w-0">
          <span
            className="h-7 w-7 shrink-0 rounded-lg flex items-center justify-center"
            style={{
              background: "var(--nxt-chip-bg)",
              border: "1px solid var(--nxt-border-soft)",
            }}
          >
            <Icon size={12} style={{ color: accent }} />
          </span>
          <h3
            className="text-[13.5px] font-medium tracking-tight truncate"
            style={{ color: "var(--nxt-fg)" }}
          >
            {item.name}
          </h3>
        </div>
        <span
          className="mono text-[9.5px] tracking-[0.22em] uppercase shrink-0"
          style={{ color: "var(--nxt-fg-faint)" }}
        >
          {KIND_META[item.kind]?.label || item.kind}
        </span>
      </div>
      <p
        className="text-[12.5px] leading-relaxed mb-2.5 line-clamp-3"
        style={{ color: "var(--nxt-fg-dim)" }}
      >
        {item.description}
      </p>
      <div className="flex items-center justify-between mt-auto pt-1">
        <span
          className="mono text-[10px] tracking-[0.18em] uppercase truncate"
          style={{ color: "var(--nxt-fg-faint)" }}
        >
          {item.category}
        </span>
        <ChevronRight
          size={12}
          className="opacity-0 group-hover:opacity-100 transition-opacity"
          style={{ color: "var(--nxt-fg-dim)" }}
        />
      </div>
    </article>
  );
}
