"""Chrome / Firefox extension (Manifest V3) scaffold."""
from typing import List


def files(project_name: str = "NXT1 Project") -> List[dict]:
    return [
        {"path": "manifest.json", "content": _MANIFEST.replace("{{name}}", project_name)},
        {"path": "popup.html", "content": _POPUP_HTML.replace("{{name}}", project_name)},
        {"path": "popup.js", "content": _POPUP_JS},
        {"path": "styles/popup.css", "content": _POPUP_CSS},
        {"path": "background.js", "content": _BACKGROUND_JS},
        {"path": "content.js", "content": _CONTENT_JS},
        {"path": "README.md", "content": _README.replace("{{name}}", project_name)},
    ]


_MANIFEST = """{
  \"manifest_version\": 3,
  \"name\": \"{{name}}\",
  \"version\": \"0.1.0\",
  \"description\": \"Built with NXT1\",
  \"action\": { \"default_popup\": \"popup.html\" },
  \"background\": { \"service_worker\": \"background.js\" },
  \"content_scripts\": [
    { \"matches\": [\"<all_urls>\"], \"js\": [\"content.js\"] }
  ],
  \"permissions\": [\"storage\", \"activeTab\"]
}
"""

_POPUP_HTML = """<!doctype html>
<html>
  <head>
    <meta charset=\"utf-8\" />
    <link rel=\"stylesheet\" href=\"styles/popup.css\" />
    <title>{{name}}</title>
  </head>
  <body>
    <div class=\"shell\">
      <span class=\"pill\">NXT1 // EXTENSION</span>
      <h1>{{name}}</h1>
      <p>Popup ready. Tell NXT1 what this extension should do.</p>
    </div>
    <script src=\"popup.js\"></script>
  </body>
</html>
"""

_POPUP_JS = """// Popup entry point
console.log('NXT1 extension popup ready');
"""

_POPUP_CSS = """:root {
  --bg: #1F1F23;
  --fg: #FAFAFA;
  --muted: #8A8A93;
  --accent: #5EEAD4;
}
body {
  width: 320px;
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: 'Inter', system-ui, sans-serif;
}
.shell { padding: 18px 18px 22px; }
.pill {
  display: inline-block;
  font-family: monospace;
  font-size: 10px;
  letter-spacing: 2.4px;
  color: var(--muted);
  border: 1px solid rgba(255,255,255,0.12);
  padding: 4px 8px;
  border-radius: 4px;
  margin-bottom: 16px;
}
h1 { margin: 0 0 8px; font-size: 22px; letter-spacing: -0.5px; }
p { margin: 0; color: var(--muted); font-size: 13px; line-height: 1.5; }
"""

_BACKGROUND_JS = """// Service worker (background)
chrome.runtime.onInstalled.addListener(() => {
  console.log('NXT1 extension installed');
});
"""

_CONTENT_JS = """// Content script
console.log('NXT1 content script active on', location.hostname);
"""

_README = """# {{name}}

Manifest V3 extension foundation generated by NXT1.

Load unpacked: `chrome://extensions` → Developer mode → Load unpacked → select this folder.
"""
