"""Expo + React Native scaffold — mobile-first foundation."""
from typing import List


def files(project_name: str = "NXT1 Project") -> List[dict]:
    return [
        {"path": "package.json", "content": _PACKAGE_JSON.replace("{{name}}", _slug(project_name))},
        {"path": "app.json", "content": _APP_JSON.replace("{{name}}", project_name).replace("{{slug}}", _slug(project_name))},
        {"path": "App.js", "content": _APP_JS.replace("{{name}}", project_name)},
        {"path": "babel.config.js", "content": _BABEL_CONFIG},
        {"path": "README.md", "content": _README.replace("{{name}}", project_name)},
    ]


def _slug(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-") or "nxt1-mobile"


_PACKAGE_JSON = """{
  \"name\": \"{{name}}\",
  \"version\": \"0.1.0\",
  \"main\": \"node_modules/expo/AppEntry.js\",
  \"scripts\": {
    \"start\": \"expo start\",
    \"android\": \"expo start --android\",
    \"ios\": \"expo start --ios\",
    \"web\": \"expo start --web\"
  },
  \"dependencies\": {
    \"expo\": \"~51.0.28\",
    \"expo-status-bar\": \"~1.12.1\",
    \"react\": \"18.2.0\",
    \"react-native\": \"0.74.5\"
  }
}
"""

_APP_JSON = """{
  \"expo\": {
    \"name\": \"{{name}}\",
    \"slug\": \"{{slug}}\",
    \"version\": \"1.0.0\",
    \"orientation\": \"portrait\",
    \"userInterfaceStyle\": \"dark\",
    \"backgroundColor\": \"#1F1F23\",
    \"splash\": { \"backgroundColor\": \"#1F1F23\" }
  }
}
"""

_APP_JS = """import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.pill}>NXT1 // EXPO + RN</Text>
      <Text style={styles.h1}>{{name}}</Text>
      <Text style={styles.body}>
        Tell NXT1 what to build. The AI extends this mobile foundation.
      </Text>
      <StatusBar style=\"light\" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1F1F23',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  pill: {
    color: 'rgba(255,255,255,0.55)',
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 2.4,
    marginBottom: 24,
  },
  h1: {
    color: '#fff',
    fontSize: 36,
    fontWeight: '700',
    letterSpacing: -1,
    textAlign: 'center',
    marginBottom: 12,
  },
  body: { color: 'rgba(255,255,255,0.55)', fontSize: 16, textAlign: 'center' },
});
"""

_BABEL_CONFIG = """module.exports = function(api) {
  api.cache(true);
  return { presets: ['babel-preset-expo'] };
};
"""

_README = """# {{name}}

Expo + React Native foundation generated by NXT1.

```
npm install
npm start
```
Scan the QR code with the Expo Go app on your device.
"""
