"""Next.js 14 (app router) + Tailwind scaffold — SaaS / dashboard / marketing."""
from typing import List


def files(project_name: str = "NXT1 Project") -> List[dict]:
    slug = _slug(project_name)
    return [
        {"path": "package.json", "content": _PACKAGE_JSON.replace("{{name}}", slug)},
        {"path": "next.config.js", "content": _NEXT_CONFIG},
        {"path": "tailwind.config.js", "content": _TAILWIND_CONFIG},
        {"path": "postcss.config.js", "content": _POSTCSS_CONFIG},
        {"path": "app/layout.jsx", "content": _LAYOUT_JSX.replace("{{name}}", project_name)},
        {"path": "app/page.jsx", "content": _PAGE_JSX.replace("{{name}}", project_name)},
        {"path": "app/globals.css", "content": _GLOBALS_CSS},
        {"path": "README.md", "content": _README.replace("{{name}}", project_name)},
    ]


def _slug(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-") or "nxt1-app"


_PACKAGE_JSON = """{
  \"name\": \"{{name}}\",
  \"private\": true,
  \"version\": \"0.1.0\",
  \"scripts\": {
    \"dev\": \"next dev\",
    \"build\": \"next build\",
    \"start\": \"next start\"
  },
  \"dependencies\": {
    \"next\": \"^14.2.5\",
    \"react\": \"^18.3.1\",
    \"react-dom\": \"^18.3.1\"
  },
  \"devDependencies\": {
    \"autoprefixer\": \"^10.4.19\",
    \"postcss\": \"^8.4.41\",
    \"tailwindcss\": \"^3.4.10\"
  }
}
"""

_NEXT_CONFIG = """/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
"""

_TAILWIND_CONFIG = """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
"""

_POSTCSS_CONFIG = """module.exports = {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
"""

_LAYOUT_JSX = """import './globals.css';

export const metadata = { title: '{{name}}', description: 'Built with NXT1.' };

export default function RootLayout({ children }) {
  return (
    <html lang=\"en\">
      <body>{children}</body>
    </html>
  );
}
"""

_PAGE_JSX = """export default function Home() {
  return (
    <main className=\"min-h-screen bg-[#1F1F23] text-white grid place-items-center px-6\">
      <div className=\"max-w-xl\">
        <span className=\"inline-block text-[11px] font-mono tracking-[0.22em] uppercase text-white/50 border border-white/15 px-2.5 py-1 rounded-sm mb-6\">
          NXT1 // NEXT.JS + TAILWIND
        </span>
        <h1 className=\"text-5xl sm:text-6xl font-bold tracking-tight leading-[1.05] bg-gradient-to-br from-white to-[#5EEAD4] bg-clip-text text-transparent\">
          {{name}}
        </h1>
        <p className=\"text-white/55 text-[17px] mt-4\">
          Tell NXT1 what to build. The AI extends this Next.js foundation.
        </p>
      </div>
    </main>
  );
}
"""

_GLOBALS_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;

html, body { height: 100%; font-family: 'Inter', system-ui, sans-serif; }
"""

_README = """# {{name}}

Next.js 14 + Tailwind foundation generated by NXT1.

```
npm install
npm run dev
```
"""
