"""React + Vite + Tailwind scaffold — SPA foundation."""
from typing import List


def files(project_name: str = "NXT1 Project") -> List[dict]:
    return [
        {"path": "index.html", "content": _INDEX_HTML.replace("{{name}}", project_name)},
        {"path": "package.json", "content": _PACKAGE_JSON.replace("{{name}}", _slug(project_name))},
        {"path": "vite.config.js", "content": _VITE_CONFIG},
        {"path": "tailwind.config.js", "content": _TAILWIND_CONFIG},
        {"path": "postcss.config.js", "content": _POSTCSS_CONFIG},
        {"path": "src/main.jsx", "content": _MAIN_JSX},
        {"path": "src/App.jsx", "content": _APP_JSX.replace("{{name}}", project_name)},
        {"path": "src/index.css", "content": _INDEX_CSS},
        {"path": "README.md", "content": _README.replace("{{name}}", project_name)},
    ]


def _slug(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-") or "nxt1-app"


_INDEX_HTML = """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>{{name}}</title>
  </head>
  <body>
    <div id=\"root\"></div>
    <script type=\"module\" src=\"/src/main.jsx\"></script>
  </body>
</html>
"""

_PACKAGE_JSON = """{
  \"name\": \"{{name}}\",
  \"private\": true,
  \"version\": \"0.1.0\",
  \"type\": \"module\",
  \"scripts\": {
    \"dev\": \"vite\",
    \"build\": \"vite build\",
    \"preview\": \"vite preview\"
  },
  \"dependencies\": {
    \"react\": \"^18.3.1\",
    \"react-dom\": \"^18.3.1\"
  },
  \"devDependencies\": {
    \"@vitejs/plugin-react\": \"^4.3.1\",
    \"autoprefixer\": \"^10.4.19\",
    \"postcss\": \"^8.4.41\",
    \"tailwindcss\": \"^3.4.10\",
    \"vite\": \"^5.4.2\"
  }
}
"""

_VITE_CONFIG = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
"""

_TAILWIND_CONFIG = """/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
"""

_POSTCSS_CONFIG = """export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
"""

_MAIN_JSX = """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"""

_APP_JSX = """export default function App() {
  return (
    <main className=\"min-h-screen bg-[#1F1F23] text-white grid place-items-center px-6\">
      <div className=\"max-w-xl\">
        <span className=\"inline-block text-[11px] font-mono tracking-[0.22em] uppercase text-white/50 border border-white/15 px-2.5 py-1 rounded-sm mb-6\">
          NXT1 // REACT + VITE
        </span>
        <h1 className=\"text-5xl sm:text-6xl font-bold tracking-tight leading-[1.05] bg-gradient-to-br from-white to-[#5EEAD4] bg-clip-text text-transparent\">
          {{name}}
        </h1>
        <p className=\"text-white/55 text-[17px] mt-4\">
          Tell NXT1 what to build. The AI extends this foundation in place.
        </p>
      </div>
    </main>
  );
}
"""

_INDEX_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;

html, body, #root { height: 100%; }
body { font-family: 'Inter', system-ui, -apple-system, sans-serif; }
"""

_README = """# {{name}}

React + Vite + Tailwind foundation generated by NXT1.

```
npm install
npm run dev
```
"""
