"""Static HTML/CSS/JS scaffold — the default for portfolios and simple sites."""
from typing import List


def files(project_name: str = "NXT1 Project") -> List[dict]:
    return [
        {"path": "index.html", "content": _INDEX_HTML.replace("{{name}}", project_name)},
        {"path": "styles/main.css", "content": _STYLES_CSS},
        {"path": "scripts/app.js", "content": _APP_JS},
        {"path": "README.md", "content": _README.replace("{{name}}", project_name)},
    ]


_INDEX_HTML = """<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>
  <title>{{name}}</title>
  <link rel=\"stylesheet\" href=\"styles/main.css\" />
</head>
<body>
  <main class=\"shell\">
    <header>
      <span class=\"pill\">NXT1 // FOUNDATION</span>
      <h1>{{name}}</h1>
      <p>Tell NXT1 what to build. The AI extends this foundation in place.</p>
    </header>
  </main>
  <script src=\"scripts/app.js\"></script>
</body>
</html>
"""

_STYLES_CSS = """:root {
  --bg: #1F1F23;
  --fg: #FAFAFA;
  --muted: #8A8A93;
  --accent: #5EEAD4;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { height: 100%; }
body {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  background: var(--bg);
  color: var(--fg);
  display: grid;
  place-items: center;
  padding: 32px;
  line-height: 1.5;
}
.shell { max-width: 720px; }
.pill {
  display: inline-block;
  font: 600 11px/1 'JetBrains Mono', monospace;
  letter-spacing: 0.22em;
  padding: 6px 10px;
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 4px;
  color: var(--muted);
  margin-bottom: 24px;
}
h1 {
  font-size: clamp(40px, 6vw, 64px);
  letter-spacing: -0.03em;
  line-height: 1.05;
  background: linear-gradient(120deg, #E8E8EE, var(--accent));
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
  margin-bottom: 16px;
}
p { color: var(--muted); font-size: 17px; max-width: 56ch; }
"""

_APP_JS = "// Static site scaffold\nconsole.log('NXT1 web-static foundation ready');\n"

_README = """# {{name}}

Generated by NXT1 (web-static foundation).

Serve with any static host or `python3 -m http.server`.
"""
